#Cấu hình AUTO TESTING IMD
#Tue Aug 04 11:24:58 ICT 2026
app.dataDir=data
app.outputDir=outputs
runner.defaultTimeoutMs=15000
preview.afterEachStep=true
env.USERNAME=admin
runner.slowMotionMs=120
template.defaultFile=sample-data/AUTO_TESTING_IMD_BanHang_CayChucNang.xlsx
runner.maxParallel=2
env.BASE_URL=https\://example.com
app.name=AUTO TESTING IMD
runner.headless=false
